# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 14:26
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.IntegerField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('answer_value', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('latency', models.IntegerField(null=True)),
                ('recording_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('date_joined', models.DateTimeField(null=True)),
                ('language', models.TextField(null=True)),
                ('time_slot', models.TimeField(null=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True)),
                ('date_of_birth', models.DateTimeField(null=True)),
                ('grade_at_registration', models.IntegerField(null=True)),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True)),
                ('family_size', models.IntegerField(null=True)),
                ('father_occupation', models.TextField(null=True)),
                ('mother_occupation', models.TextField(null=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slate2learn.Centre')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('credits', models.DecimalField(decimal_places=2, max_digits=20)),
                ('credit_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slate2learn.Learner')),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slate2learn.Learner'),
        ),
    ]
