# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slate2learn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='question',
            new_name='question_id',
        ),
    ]
